const disciplinesList = [
  "differential equations",
  "mammalogy",
  "human-computer interaction",
  "conservation biology",
  "sleep medicine",
  "cell signalling",
  "physicochemical",
  "atomic physics",
  "tectonics",
  "ion channels",
  "computational geometry",
  "quantum electrodynamics",
  "radiochemistry",
  "integrative biology",
  "mathematical statistics",
  "neuropeptides",
  "quantum computing",
  "drug discovery",
  "ionization physics",
  "cultural and ethnic studies",
  "femtochemistry",
  "materials science",
  "resting state",
  "optical fibres",
  "geology",
  "commutative algebra",
  "nuclear chemistry",
  "limit theory",
  "quantum algebra",
  "surface chemistry",
  "infectious diseases",
  "atmospheric sciences",
  "civil engineering",
  "optics",
  "predictive analytics",
  "quantum optics",
  "numerical analysis",
  "solid state",
  "flow chemistry",
  "metabolic regulation",
  "ultracold atoms",
  "bacterial",
  "crystallography",
  "bacteria",
  "system biology",
  "business",
  "area studies",
  "multimedia",
  "microbiology",
  "habitable zone",
  "psychophysiology",
  "sonochemistry",
  "mathematical chemistry",
  "transportation",
  "malaria",
  "environmental science",
  "stochastic processes",
  "gender and sexuality studies",
  "geostatistics",
  "anthropology",
  "quantum devices",
  "geomicrobiology",
  "darkenergy",
  "scanning probe microscopy",
  "physiology",
  "photochemistry",
  "biodiversity",
  "computational neuroscience",
  "economics",
  "history",
  "chemical biology",
  "nonparametric inference",
  "population genetics",
  "quantum channels",
  "genomics",
  "neurobiology",
  "complexity theory",
  "crowdsourcing",
  "risk management",
  "flavor chemistry",
  "group theory",
  "cardiology",
  "wave optics",
  "solitons",
  "metric geometry",
  "growth and synthesis",
  "geophysics",
  "molecular mechanics",
  "stochastic analysis",
  "classical mechanics",
  "geochronology",
  "gamma rays",
  "asymptotic inference",
  "communication and control",
  "applied mathematics",
  "web servers",
  "electrochemistry",
  "machine learning",
  "official statistics",
  "ultrashort pulses",
  "digital libraries",
  "bioengineering",
  "climatology",
  "windpower",
  "theoretical computer science",
  "parallel computing",
  "dynamical systems",
  "petrology",
  "quantum information",
  "portfolio management",
  "volcanology",
  "cognitive science",
  "statistical finance",
  "cryptography",
  "communication studies",
  "ultrafast phenomena",
  "computer vision",
  "gaming",
  "mathematcics",
  "philosophy",
  "quantum field theory",
  "biophysics",
  "sustainability",
  "soil science",
  "trichology",
  "general finance",
  "sedimentology",
  "bioinformatics",
  "computation and language",
  "law",
  "statistical computation",
  "fiber optics",
  "cosmology",
  "mechanochemistry",
  "algorithms",
  "hair transplantation",
  "archaeology",
  "survival analysis",
  "oncology",
  "gynecology",
  "topological quantum states",
  "atmospheric chemistry",
  "quality control",
  "computational finance",
  "obstetrics",
  "evolutionary biology",
  "stellar astronomy",
  "short-presentations",
  "kernelization",
  "methodology",
  "nonlinear science",
  "standard model",
  "representation theory",
  "symbolic computation",
  "supersymmetry",
  "galactic astronomy",
  "supramolecular chemistry",
  "extragalactic astronomy",
  "entomology",
  "web conferencing",
  "radiobiology",
  "tourism",
  "atom optics",
  "chemo-informatics",
  "queues",
  "proteins",
  "collective intelligence",
  "agrochemistry",
  "experimental designs",
  "biomaterials",
  "optimization and control",
  "self-organizing systems",
  "hepatology",
  "renewable energy",
  "solar physics",
  "atomic clocks",
  "neurology",
  "programming language theory",
  "agriculture",
  "particle physics",
  "addication",
  "autoimmunity",
  "fluid dynamics",
  "psychology",
  "inorganic chemistry",
  "quantum networks",
  "cosmic rays",
  "systems security",
  "social networks",
  "electronics",
  "haematology",
  "quantum chromodynamics",
  "cart",
  "ultra-high energy",
  "general biology",
  "quantum cryptography",
  "language",
  "programming",
  "ergodic theory",
  "ethology",
  "combinatorics",
  "geomorphology",
  "botany",
  "political science",
  "probability",
  "aeronautics",
  "web services",
  "philosophical",
  "quantum algorithms",
  "applied statistics",
  "developmental biology",
  "image processing",
  "microbial stresses",
  "transit light curves",
  "quantum information processing",
  "open quantum systems",
  "testing of hypotheses",
  "naturalproduct chemistry",
  "statistical mechanics",
  "differential geometry",
  "embryology",
  "wind energy",
  "operating systems",
  "stochastic finance",
  "text mining",
  "limnology",
  "history of cosmic ray research",
  "m-theory",
  "aerobiology",
  "parametric inference",
  "oligonucleotides",
  "environmental biology",
  "string theory",
  "game theory",
  "information theory",
  "balloon and satellite measurements",
  "plasma physics",
  "endocrinology",
  "analytical chemistry",
  "accelerators",
  "electromagnetism",
  "neurochemistry",
  "dementia",
  "marine geology",
  "occupational health",
  "quantum electronics",
  "e-commerce",
  "stochastic PDE",
  "devices and applications",
  "complex systems",
  "animation",
  "development studies",
  "salford systems",
  "descriptive statistics",
  "special relativity",
  "complex networks",
  "algebraic geometry",
  "environmental geotechnology",
  "condensed matter",
  "anatomy",
  "pathobiology",
  "quantitative finance",
  "systems and control",
  "trading and market microstructure",
  "spectral theory",
  "schroedinger equation",
  "pneumococci",
  "software engineering",
  "quantum discord",
  "environmental pollution",
  "peptides",
  "mechatronics",
  "databases",
  "evolutionary dynamics",
  "phytopathology",
  "psychobiology",
  "treenet",
  "brain disorders",
  "network science",
  "business studies",
  "thermochemistry",
  "geometric topology",
  "complex variables",
  "geography",
  "many body systems",
  "international studies",
  "physical chemistry",
  "cosmochemistry",
  "pharmacology",
  "applied optics",
  "public health",
  "neuroimaging",
  "ophthalmology",
  "differential games",
  "petrochemistry",
  "laser physics",
  "systems biology",
  "multiagent systems",
  "internet architecture",
  "industrial relations",
  "virology",
  "neuroscience",
  "cardiovascular diseases",
  "marine chemistry",
  "classical analysis",
  "synthetic chemistry",
  "optical lattices",
  "salford predictive modeler",
  "data mining conference",
  "meteorology",
  "arts",
  "nutrition science",
  "climate change",
  "analytics",
  "Space Science",
  "palynology",
  "pediatrics",
  "surgery",
  "astrobiology",
  "ichthyology",
  "tumor microenvironment",
  "dynamic economic models",
  "programming languages",
  "knowledge management",
  "statistical computing",
  "colloids",
  "geochemistry",
  "hardware architecture",
  "biomechanics",
  "reliability",
  "planetary science",
  "supernova",
  "discrete mathematics",
  "estimation theory",
  "general topology",
  "biosynthesis",
  "light-matter interaction",
  "chemical physics",
  "sociobiology",
  "mantle plumes",
  "e-learning",
  "statistical physics",
  "stochastic dynamics",
  "hydrology",
  "time series",
  "nephrology",
  "quantum biology",
  "quantum metrology",
  "transplantation",
  "nanophotonics",
  "logic",
  "legal management",
  "toxicology",
  "estimation",
  "algebraic topology",
  "optimal control",
  "cancer",
  "robotics",
  "stratigraphy",
  "operator algebras",
  "biophotonics",
  "histochemistry",
  "coherent light sources",
  "oceanography",
  "neurogenesis",
  "computer simulations",
  "virtual reality",
  "symplectic geometry",
  "mars",
  "quantum magnetism",
  "operations research",
  "molecular biology",
  "visual arts",
  "epigenetics",
  "graphics",
  "hydrogeology",
  "quantum measurement",
  "light storage",
  "sound",
  "mechanical oscillators",
  "field theory",
  "quantum hall effect",
  "neurosurgery",
  "quantum memory",
  "number theory",
  "optimization",
  "graph theory",
  "k-theory and homology",
  "stem cells",
  "networks security",
  "theoretical physics",
  "computational engineering",
  "ornithology",
  "graphene",
  "cellular automata",
  "natural disasters",
  "formal languages",
  "pathology",
  "regression",
  "ubiquitin",
  "statistical genetics",
  "metrology",
  "linear models",
  "nanophysics",
  "astrochemistry",
  "structural studies",
  "black holes",
  "genetic programming",
  "bussiness",
  "literature",
  "distributed computing",
  "micropaleontology",
  "gastroenterology",
  "user interfaces",
  "anesthesiology",
  "photon science",
  "bifurcation theory",
  "functional analysis",
  "fixed parameter tractability",
  "organometallic chemistry",
  "psychiatrists",
  "arachnology",
  "pattern recognition",
  "topological quantum systems",
  "acoustics",
  "cell biology",
  "drug delivery",
  "critical care medicine",
  "analysis",
  "low-dimensional systems",
  "nuclear structure and reaction mechanism",
  "space exploration",
  "media studies",
  "audio",
  "environmental engineering",
  "applied probability",
  "modeling and control systems",
  "performing arts",
  "biostatistics",
  "mycology",
  "herpetology",
  "glaciology",
  "molecular physics",
  "3d imaging",
  "public administration",
  "applied stochastic processes",
  "anova",
  "thermodynamics",
  "quantum physics",
  "mathematical software",
  "parametric down-conversion",
  "loop quantum gravity",
  "geodesy",
  "nuclear physics",
  "integrated optics",
  "paleontology",
  "dark matter",
  "bayesian inference",
  "geriatrics",
  "nanotechnology",
  "materials chemistry",
  "computational complexity",
  "immunology",
  "mathematical biology",
  "extremal combinatorics",
  "flashtalks",
  "nanoscience",
  "biosensors",
  "quantum simulations",
  "sequential analysis",
  "data structures and algorithms",
  "statistical inference",
  "security",
  "chaotic dynamics",
  "ecology",
  "neurofeedback",
  "rheumatology",
  "data mining",
  "phytochemistry",
  "survey sampling",
  "information retrieval",
  "histology",
  "dermatology",
  "cognitive neuroscience",
  "econometrics",
  "criminology",
  "pricing of securities",
  "sociology",
  "category theory",
  "hydrogenation chemistry",
  "population biology",
  "analysis of PDEs",
  "religion",
  "parasitology",
  "inflammation",
  "oenology",
  "general mathematics",
  "immunochemistry",
  "operator theory",
  "emerging technologies",
  "data analysis",
  "demography",
  "cancer metabolism",
  "marketing",
  "epidemiology",
  "organic chemistry",
  "molecular imaging",
  "quantum error correction",
  "pulmonology",
  "industry",
  "drug addiction",
  "cell fate",
  "antibody",
  "software",
  "automata theory",
  "mineralogy",
  "stochastic calculus",
  "neurotoxicology",
  "lattice gases",
  "mathematical physics",
  "bell inequalities",
  "zoology",
  "rings and algebras",
  "statistics",
  "multivariate analysis",
  "emergency medicine",
  "signalling networks",
  "general relativity",
  "building biology",
  "photobiology",
  "staitstical genetics",
  "astrophysics",
  "artificial intelligence",
  "astrostatistics",
  "geomagnetics",
  "pattern formation",
  "non-locality",
  "reliability theory",
  "nonlinear optics",
  "chemical engineering",
  "autophagy",
  "life sciences",
  "space probes",
  "synchrotron radiation",
  "biogeography",
  "library science",
  "collective behavior",
  "evolutionary computing",
  "electrical engineering",
  "plate tectonics",
  "prostate cancer",
  "nanomedicine",
  "paleoclimatology",
  "trauma care",
  "geometric group theory",
  "occupational safety",
  "accounting",
  "nanomechanics",
  "education",
  "health care",
  "social and information networks",
  "polymer chemistry",
  "biochemistry",
  "mitochondrial metabolism",
  "balloon experiments",
  "linguistics",
  "immunity",
  "crisis management",
  "hydraulics",
  "solid state physics",
  "seismology",
  "solar power",
  "structural biology",
  "genetics",
  "population ecology",
  "green chemistry",
  "cryobiology",
  "marine biology",
  "multi-agent systems",
  "exoplanets",
  "photonics",
  "entertainment",
  "randomforests",
  "light squeezing",
  "marine microbes",
  "environmental chemistry",
  "cavity qed",
  "psychiatry",
  "biotechnology",
  "foundations of quantum physics",
  "algebra",
  "abstract algebra",
  "linear algebra",
  "calculus",
  "geometry",
  "topology",
  "arithmetic",
  "modeling and simulation",
  "systems biology",
  "computational mathematics",
  "automation",
  "control systems",
  "neural networks",
  "pattern recognition",
  "operational research",
  "teaching mathematics",
  "lasers",
  "plasma",
  "self-organisation",
  "radiation protection",
  "microscopy",
  "safety",
  "applied physics",
  "medical physics",
  "neutrons",
  "teaching physics",
  "magnetic materials",
  "electrostatics",
  "catalysis",
  "chemoinformatics",
  "computational chemistry",
  "combinatorial chemistry",
  "industrial chemistry",
  "molecular modeling",
  "colloids",
  "polymers",
  "spectroscopy",
  "mass spectroscopy",
  "nmr",
  "cosmetic chemistry",
  "water treatment",
  "building materials",
  "synthetic materials",
  "chromatography",
  "plastic processing",
  "hazardous materials",
  "waste management",
  "teaching chemistry",
  "optoelectronics",
  "display devices",
  "microtechnology",
  "automotive engineering",
  "railways",
  "aviation",
  "spaceflight",
  "mineral processing",
  "metallurgy",
  "electric power",
  "nuclear energynuclear technology",
  "energy production",
  "ecosystems",
  "sustainable development",
  "computational biology",
  "agronomy",
  "food production",
  "food chemistry",
  "nursing",
  "dentistry",
  "nuclear medicine",
  "radiation therapy",
  "radiology",
  "nuclear magnetic resonance imaging",
  "tomography",
  "sonography",
  "mammography",
  "foundations of computer science",
  "information technology",
  "cloud computing",
  "sensor networks",
  "human-computer interaction",
  "natural language processing",
  "computing hardware",
  "computer graphics",
  "e-learning",
  "human resource management",
  "computational physics",
  "numerical simulation",
  "nanomaterials",
  "semiconductors",
  "aerospace",
  "circuits",
  "computational intelligence",
  "computational linguistics",
  "computer architecture",
  "control theory",
  "cybernetics",
  "data management",
  "database",
  "digital multimedia",
  "e-business",
  "embedded systems",
  "e-health",
  "evolutionary computation",
  "fuzzy systems",
  "green computing",
  "grid computing",
  "high performance computing",
  "information systems",
  "intelligent systems",
  "knowledge discovery",
  "knowledge engineering",
  "knowledge representation",
  "mobile computing",
  "network security",
  "open source",
  "open science",
  "pervasive computing",
  "power engineering",
  "privacy",
  "signal processing",
  "ubiquitous computing",
  "wireless",
  "methods and protocols",
  "metabolism",
  "metabolic diseases",
  "plant biology",
  "synthetic biology",
  "science policy",
  "clinical genetics",
  "pharmaceutical chemistry",
  "plant science",
  "family practice",
  "materials engineering",
  "diabetes",
  "urology",
  "materials physics",
  "cardiovascular medicine",
  "allergy",
  "internal medicine",
  "biomedical engineering",
  "nutrition",
  "nanobiology",
  "electronic materials",
  "clinical immunology",
  "industrial microbiology",
  "metabolic diseases",
  "atmospheric science",
  "applied chemistry",
  "hypertension",
  "solid earth science",
  "atomic and molecular physics",
  "preventive medicine"
];

export default disciplinesList;
